### PR TITLE
Replace echo -n with printf

### PR DESCRIPTION
**Pull request by vonhraban**
`echo` does not have consistent behavior since some bash shells do not recognise `-n` flag, also echo can be used as a binary `/bin/echo` and therefore there is no guarantee that it would respect -n flag.
`printf` has consistent behaviour on all systems.

Even though the shebang specifies `!/usr/bin/env bash` I still had an issue on a brand new install running MacOS BigSur when I changed the default bash to /bin/bash. Instead of omitting the newline, it was printing `-n` followed by a string and a newline. Somehow on a previous BugSur installation with seemingly identical setup `-n` flag was respected.

And of course, thank you so much for an amazing work maintaining this super awesome and minimalistic prompt!

### CODE REVIEW

**Comment by rpdelaney** [comment]
I tend to agree with this. Let's see what Todd thinks.

There are other uses of `echo -n` on line 176 and 198 by the way.

**Comment by twolfson** [comment]
Looks good at a glance. Kind of surprised Big Sur is having this issue o_o

I do want to dig into the `echo` vs `printf` docs a little more before accepting this, since `printf` does do more than just restating content

Also, as @rpdelaney said, there were a couple `echo -n` missed (see `git grep "echo -n"`) but I'm sure we can fix those when landing if not resolved by then

Will take a look at by the end of the weekend (though prob tonight or tomorrow)

**Comment by vonhraban** [comment]
Hello everyone 👋 
I pushed another change that takes care of the remaining usages of `echo -n`. In fact, even though it hardly gives us anything, it could be beneficial to also replace `echo` without `-n` flag with `printf` because otherwise it just looks strange inconsistent. But perhaps it's more hassle that it's worth.

As of Big Sur, I had two fresh installs since it was released and it was working fine on one but not the other. The OSes might have been some minor versions apart, it is hard to say now

**Comment by twolfson** [comment]
Dug into manual page of `printf` and found an edge case that it won't work for =/

`printf` will do string replacement for a lot of content with leading `\` and some with `%`

I couldn't create a branch with `\` in it but I was able to make one with `%b` in it

```
todd at Euclid in ~/tmp/git-printf-test on master△
$ git checkout -b "test\\foo"
fatal: 'test\foo' is not a valid branch name.
todd at Euclid in ~/tmp/git-printf-test on master△
$ git checkout -b "test%bfoo"
Switched to a new branch 'test%bfoo'
todd at Euclid in ~/tmp/git-printf-test on test%bfoo△
$ 
```

When switching to this PR, the `%b` text is lost =/

```
todd at Euclid in ~/tmp/git-printf-test on testfoo△
$ 
```

So we should try to find a solution which does no parsing/replacement =/

@vonhraban What does `man echo` on Big Sur point to? (though sometimes `bash` `echo` might also be a non-builtin (or maybe I'm thinking of `true`))

**Comment by twolfson** [comment]
Ah, the fix seems to either be:

- Use `echo -e "text \c"`, which I dislike due to it using `-e` which enables escape commands in `echo` which can lead to more headaches
    - https://stackoverflow.com/a/59038720/1960509
- Use `printf "%s" "text"`, this way we avoid the entire replacement issue by providing what to replace ;D
    - https://stackoverflow.com/a/59038720/1960509
    - This seems like a good hack
    - It does restore the `%b` from the edge case

@vonhraban Can you confirm that will work for you?

**Comment by rpdelaney** [comment]
Yes, I had a twinge that `printf "%s" "text"` is the preferred way to do this but I couldn't remember why. 

Edit: Let's make sure there's a test for this case yeah?

Edit 2: This issue is also referenced in [Bash Pitfalls](https://mywiki.wooledge.org/BashPitfalls#printf_.22.24foo.22) on Greg's wiki

**Comment by twolfson** [comment]
It's been 6 weeks since this was last updated. Closing for now since we never got a suitable replication environment

Feel free to reopen if it's still needed

**Pull request closed without merging**
