### PR TITLE
Updated single line install to recreate temp directory when make is not installed

### PR DESCRIPTION
**Pull request by tnatanael**
As the title says

### CODE REVIEW

**Comment by rpdelaney** [comment]
Looks like this just adds `rm -rf sexy-bash-prompt` to the one-line install command. I'm not sure how to square that with your description. Can you explain a bit more please?

**Comment by tnatanael** [comment]
Sure! When we try the command without make installed, git creates the folder, so, to run again we need to delete this folder...
This change avoids it!

**Comment by rpdelaney** [comment]
Arguably it would be better to explicitly list `make` as an installation dependency. In the "manual install" section we call `make` again.

**Comment by tnatanael** [comment]
This is clear when the install fails... But... When you run the single LINE install command again It fails because of the folder exists, the rm solves It!

**Comment by rpdelaney** [comment]
I understand. What I'm suggesting is that you might not have had that problem if we had called out make as an install dependency.

**Comment by twolfson** [comment]
:+1: to both proposed options. Even more options:

- Switch from `rm -rf sexy-bash-prompt && git clone` to `(test -d sexy-bash-prompt || git clone)` to cut down on bandwidth reuse
    - It's very unlikely someone will be upgrading without having a wiped `/temp` folder
- Drop `make` entirely, we aren't using it except as a large script container (would make PR much larger)
    - Example: Simple `bash` function wrapper -- `./install.sh` (alias for `default`), `./install.sh default`, `./install.sh symlink` -- `./install.sh` would have `function _sexy_bash_prompt_install_default ()` and the last line would invoke said function

**Comment by tnatanael** [comment]
I disagree with this:
"It's very unlikely someone will be upgrading without having a wiped /temp folder"
Since the first time i run the command it fails because of not having make installed, my temp folder almost aways have the sexy-bash-prompt folder and the git clone command fails!

**Comment by twolfson** [comment]
I think you might have missed the line above that one =/ That was in the context of switching from `rm -rf sexy-bash-prompt && git clone` to `(test -d sexy-bash-prompt || git clone)` to cut down on bandwidth reuse

**Comment by tnatanael** [comment]
What test -d folder does?

**Comment by twolfson** [comment]
`test` is a built-in `bash` function which allows for performing various assertions. `test -d` verifies that a directory exists (in this case `sexy-bash-prompt`). We use the `||` to run `git clone` if it doesn't

**Comment by twolfson** [comment]
Here's the documentation (same as `man bash`):

https://www.gnu.org/software/bash/manual/html_node/Bash-Conditional-Expressions.html

`test` can also be installed as a separate command (e.g. for `sh`) but `bash` has it built-in as mentioned

**Comment by tnatanael** [comment]
Nice! Changing...

**Comment by twolfson** [comment]
@tnatanael :+1:

@rpdelaney How are you feeling on this PR? Is it good to land or do something about the `make` requirement (e.g. document, removal)?

**Comment by tnatanael** [comment]
This saturday i could make the install.sh script if you guys could w8 a little...

**Comment by rpdelaney** [comment]
I have a moderate concern and a mild one.

Mild: `[[ -d $thing ]]` is a bit more idiomatic in bash than `test -d "$thing"`. But the behavior should be the same in this case.

Moderate: Now that I've looked at it I feel like there's a growing smell about whether this is simple enough to be called a "one line install". A careful arrangement of nested subshells using `&&` and `||` in place of "and" and "or" (which they aren't, really, especially when they are chained like this) will become unmaintainable if it grows any more complex than this. Do we need tests for our "one-line" install?

In other places I've seen the one-line install be `curl -Ss https://github.com/path/to/raw/install.script | bash`. I'm not sure where exactly to draw the line but I'm not sure what we had originally is preferable to that even before this PR.

Thoughts?

**Comment by twolfson** [comment]
Using `[[ ]]` for conditionals is fine with me. I think I wrote `test -d` as it feels a little more human friendly for a command that's being copy/pasted

We're not using any logic or subshells except for the new `||` we just added. All the other `&&` are for chaining commands, nothing more.

Manual testing is good enough for this case, it's not something we have a lot of edge cases for. I think this is either the first or second bug report ever and we've had one line install since the start

I'd prefer to avoid `curl | bash`. It's practical for large installs with lots of dependencies but also makes everyone a little more paranoid when copying/pasting. It's nice here as the auditing of the code is very obvious

**Comment by twolfson** [comment]
To summarize my thoughts, let's:

- Switch from `test` to `[[ ]]` as @rpdelaney would like (also helps with consistency with library)
- Add `make` requirement documentation
- Call it a day, we've spent so much time bikeshedding ._. :shipit:

**Comment by twolfson** [comment]
I'm going to add these changes to the PR, then y'all can review and we can ship it =)

**Comment by twolfson** [comment]
Alright, ready for review =)

**Comment by rpdelaney** [comment]
First, a parting shot on the bikeshed:

> I'd prefer to avoid `curl | bash`. It's practical for large installs with lots of dependencies but also makes everyone a little more paranoid when copying/pasting. It's nice here as the auditing of the code is very obvious

I share that concern, but I still have to look in the repo to read the Makefile if I want to know what's going happen as a result of the command we have, don't I? It seems like the workflow where we clone the repo and `make install` has the same concerns attached, since arbitrary code can be executed in a Makefile just as easily as in a bash script.

### That said:

927fc97  is an uncontroversial improvement. Strict upgrades like that are rare in this life. Ship it!

**Comment by twolfson** [comment]
Ah, great counterpoint @rpdelaney. I think at that point we fall into the hole where the entire `curl | bash` security concern falls apart, e.g. people should also read our entire source code, how do they know there isn't something malicious in the `.bash_prompt` =o

Cool, landing this PR :shipit: 

Thanks for the discussion and work @tnatanael and @rpdelaney !

**Pull request merged**
