### PR TITLE
Moving from gratipay-badge onto text prompt

### PR DESCRIPTION
**Pull request by twolfson**
I have been experimenting with the positioning of my "Donating" section on my `spritesmith` repos. I adopted the same pattern as `gulp` (moving from large badge at bottom to thin text at top) and saw much more user interaction.

https://github.com/gulpjs/gulp/blob/v3.8.10/README.md

I would like to add on this configuration to `sexy-bash-prompt` (see this PR). I created a Gratipay organization to accept/distribute donations:

https://gratipay.com/sexybashprompt/

This required a Twitter account setup so we have one of those now too:

https://twitter.com/sexybashprompt

/cc @rpdelaney

### CODE REVIEW

**Comment by rpdelaney** [comment]
No comments. Not my domain :)

**Comment by twolfson** [comment]
Okie doke, going to land this then. If you want to join the Gratipay organization, let me know.

**Comment by rpdelaney** [comment]
Nah, 95%+ of the work on this is yours. If you want, donate a portion of the proceeds to Planned Parenthood or the EFF.

**Comment by twolfson** [comment]
Heh, alright, You got it.

**Pull request merged**
